### ISSUE TITLE
[Question] - esp8266 pin configuration

### ISSUE THREAD

**Issue by MagnusPer** [taligentx/dscKeybusInterface#11]
I'm a little bit confused regarding esp8266 pins to use since there is a difference in sketches vs. decriptions.
According to your description the following pins shall be used  (esp8266: D1,D2,D8), but in the Status and KeybusReader sketch D9 is used!

**In Status and Keybus Reader sketch**
#define dscClockPin 3     //esp8266 v1.0 **D9**
#define dscReadPin 4     //esp8266 v1.0 D2
#define dscWritePin 5    //esp8266 v1.0 D1

**In Status-MQTT-Homebridge sketch**
#define dscClockPin D1
#define dscReadPin D2
#define dscWritePin D8

also -  I assume it is possible to define either Dx or GPIOx, example GPIO **5** or **D1**

**Comment by taligentx** [comment]
I've updated the examples sketches to clarify, the KeybusReader and Status sketches show the Arduino pins.

> also - is it possible to either define Dx or GPIOx,example GPIO 5 or D1

Sure, you can specify the GPIO value directly - the Dx pin value is just a convenience from the Arduino/esp8266 core, they are mapped automatically to the GPIO pin number:

```
NodeMCU    GPIO
D1         5
D2         4
D8         15
```

I typically use the Dx notation to easily differentiate Arduino and esp8266 pins.
