### ISSUE TITLE
Add support for PowerSeries Neo 

### ISSUE THREAD

**Issue by connected201** [taligentx/dscKeybusInterface#111]
hi, i received today Dsc PowerSeries Neo (https://www.dsc.com/dsc-product-families/Neo/1), and tested with current firmware, as expected, it's not working...
question, it,s possible to add support for this model?
i can send to firmware developers, dsc panel to reverse new protocol. Best regards
dsc neo screens:
![IMG_20190722_135722](https://user-images.githubusercontent.com/20506433/61633404-b0565d80-ac97-11e9-88e1-15b0da188f43.jpg)
![IMG_20190722_135726](https://user-images.githubusercontent.com/20506433/61633405-b0565d80-ac97-11e9-9520-640b9833d908.jpg)
![IMG_20190722_135743](https://user-images.githubusercontent.com/20506433/61633406-b0565d80-ac97-11e9-95f6-854d1b855451.jpg)
![IMG_20190722_140300](https://user-images.githubusercontent.com/20506433/61633410-b0eef400-ac97-11e9-85f0-dd406e23e404.jpg)

**Comment by taligentx** [comment]
Hi @connected201 - please refer to the `README.md`, this has already been addressed.  Neo uses a totally different encrypted protocol so unless someone is able to crack the encryption these systems cannot be directly interfaced.

**Comment by PascalSI** [comment]
Hi @connected201 , where can i see how you made a printed circuit board for such a case?

**Comment by connected201** [comment]
hi @PascalSI , i wil made some changes, and add gsm support , and i will public all sources
