### ISSUE TITLE
[0x16] Unknown panel ....

### ISSUE THREAD

**Issue by harryzz** [taligentx/dscKeybusInterface#127]
Hello
some additional data for DSC PC1565 panel.
 4704.33: 00010110 0 00001110 00100010 11100110 00101100 [0x16] Unknown panel | Zone wiring: EOL | *8 programming

also in installation mode in section [903] Module Supervision Field:
19035.68: 00000101 0 10000001 11101111 10010001 11000111 [0x05] Partition 1: Ready Backlight - Unrecognized data: 0xEF | Partition 2: disabled
19035.75: 00001010 0 10000001 11101111 01000001 00000000 00000000 00000000 00000000 10111011 [0x0A] Ready Backlight - Unrecognized data: 0xEF | Zone lights: 1 7

- reports zones with broken supervising.

br
Zahari

**Comment by taligentx** [comment]
Hi @harryzz - late response, thanks for the data for the PC1565, added to the decoding and list of verified panels.  Also thanks for the 0xEF data, the develop branch actually already had this but still hadn't been pushed out to master.
