### ISSUE TITLE
Virtual keypad keys

### ISSUE THREAD

**Issue by PascalSI** [taligentx/dscKeybusInterface#14]
Hi, i do not quite understand how the virtual keypad keys works ... So the code set in the virtual keyboard will put the panel under guard?

Sorry for my english, i'm using an translator

**Comment by PascalSI** [comment]
I think i understand how it works, will it work with the Mosquitto server? I have a PC1616 system.

**Comment by taligentx** [comment]
Closing this one out, feel free to post a new issue if you run into any problems.
