### ISSUE TITLE
Honeywell vista support?

### ISSUE THREAD

**Issue by adamurban** [taligentx/dscKeybusInterface#156]
Commercial products like AlarmDecoder seem to be able to support both DSC and Honewell/Ademco protocols via the same physical interface. Perhaps this project could too?

So far these are the only details I could find on the honeywell protocol: https://forum.arduino.cc/index.php?topic=200820.0
Looks like it is RS232, 4800, 8 data bits, Even parity, 2 stop bits...

**Comment by Dilbert66** [comment]
here you go:

https://github.com/Dilbert66/esphome-vistaECP

**Comment by taligentx** [comment]
I've added a link to @Dilbert66's esphome-vistaECP project in the README.md, support for other security systems is currently out of scope for this library - if nothing else, I don't have the hardware to test.  If someone comes along with a PR that seamlessly integrates the protocol decoding for a different system (for example, something that doesn't inflate the compilation size for DSC systems or require changes in the existing example sketches), I'm open to merging.
