### ISSUE TITLE
New DSC Virtual Keypad Project with (read/write)

### ISSUE THREAD

**Issue by sj-louw** [taligentx/dscKeybusInterface#18]
@taligentx 

Apologies for opening a new issue, but I thought you would be interested too see this. Please feel free to close this issue.

https://github.com/sixerdoodle/DSCWIRELESSKEYPAD
http://www.jenrathbun.com/Electronics/projects/tricks-with-google-home/wireless-dsc-pc1555-keypad/

It also makes use of two PINS, one read and one write on the microcontroller side, but the circuit looks a bit different:

![image](https://user-images.githubusercontent.com/29563018/41091751-96c52a06-6a47-11e8-919c-3103524bfef1.png)

**Comment by taligentx** [comment]
Thanks for the heads-up, it's great to see more projects!  It'd be interesting to see the differences between using an optocoupler and other ways to connect to the panel - added to the todo list.

I like the idea to integrate with IFTTT - also added to the todo list.
