### ISSUE TITLE
D8 is not a good pin for input on NodeMCU

### ISSUE THREAD

**Issue by toddlipcon** [taligentx/dscKeybusInterface#268]
The NodeMCU fails to boot if D8 is pulled low. D7 seems like a bette choice according to https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

**Comment by taligentx** [comment]
Gotcha, the pin documentation was updated in `develop` back in 4d1d7fa4aa3dd7a13506c7010029a818bedb4c67 to only list single pins instead of listing a range of pins so it'll show up in `master` at the next release.
