### ISSUE TITLE
HomeAssistant - LWT offline after 24 - 48 hrs

### ISSUE THREAD

**Issue by brucehatherell** [taligentx/dscKeybusInterface#285]
I have a strange issue with Home Assitant (migrated from HomeKit) where my ESP-8266 goes offline after about 24-48 hrs … it’s not connected to serial so suspect it could be buffer related as I am still able to connect via OTA and re-flash to bring back online - have implemented buffer logs to MQTT this morning but anyone had similar issues?

**Comment by brucehatherell** [comment]
Still running into this issue on Home Assistant - removed OTA as I thought that was the cause - anyone else having their ESP8266 drop after about 24 hrs?

**Comment by brucehatherell** [comment]
Issue was mine, was not erasing esp8266 when flashing - all working great again.

**Comment by taligentx** [comment]
Hi @brucehatherell - great to hear you were able to resolve this, noting this as a troubleshooting step for future intermittent issues on the esp8266.
