### ISSUE TITLE
esp32-Poe adapter support? 

### ISSUE THREAD

**Issue by zsamiatt** [taligentx/dscKeybusInterface#305]
Hello!
The esp32-POE adapter support? I would like using the DSC with LAN.

https://www.olimex.com/Products/IoT/ESP32/ESP32-POE-ISO-EA/open-source-hardware

**Comment by taligentx** [comment]
Hi @zsamiatt - long delay, but in case the answer is useful for future readers, it seems like that module should work using the esp32 example sketches.  You'll need to set the GPIO pin numbers in the sketches to match the GPIOs that are exposed on those modules.
