### ISSUE TITLE
Hi, zones 17 to 32 don't report status. 

### ISSUE THREAD

**Issue by dockuno** [taligentx/dscKeybusInterface#31]
I think it should be openZones [2].
The same error for zones 24-32

https://github.com/taligentx/dscKeybusInterface/blob/bc2d2b7faa934e6368c9e72c20bdd722be7755dd/src/dscKeybusProcessData.cpp#L336

Thanks for the good work

**Comment by taligentx** [comment]
Hi @dockuno - good catch, that's a copy/paste error.  Thanks for the report!
