### ISSUE TITLE
wow, just what I was looking for.

### ISSUE THREAD

**Issue by nelg** [taligentx/dscKeybusInterface#46]
Not an issue, just wanted to say great work!.

I've been running an arduino connected to my DSC for about 6 years, (http://dsc.juliano.com.br/)
What you are doing with the ESP8266 is just what I was looking for.   Really excited to see this work, I'll be giving the stuff you've written a go soon.

Thanks
Glen Ogilvie

**Comment by taligentx** [comment]
@nelg @zzhang1 - Thank you!  It's great to hear your experiences.
