### ISSUE TITLE
Soft WDT reset in HomeAssistant-MQTT

### ISSUE THREAD

**Issue by witek1308** [taligentx/dscKeybusInterface#51]
Hi, on a serial console I am observing soft WDT reset periodically, there are some articles in the net about it, eg. https://github.com/esp8266/Arduino/issues/2866 which suggests issues with watchdog timer, but I don't know how to identify relevant code line for this. Any hints?

08:57:47.938 -> 
WiFi connected: 192.168.1.41
08:57:48.963 -> MQTT connected: 192.168.1.30
08:57:48.963 -> DSC Keybus Interface is online.

08:59:35.135 -> Soft WDT reset
08:59:35.135 -> 
08:59:35.135 -> ctx: cont 
08:59:35.135 -> sp: 3ffefaf0 end: 3ffefd90 offset: 01b0
08:59:35.135 -> 
08:59:35.135 -> >>>stack>>>
08:59:35.135 -> 3ffefca0:  00000007 3ffee738 3ffee610 40203ac0  
08:59:35.168 -> 3ffefcb0:  3ffefcf0 3ffee610 00000000 40201ddf  
08:59:35.168 -> 3ffefcc0:  3ffefcf0 00019a44 3ffee738 402051f4  
08:59:35.168 -> 3ffefcd0:  00000000 3fffdad0 3ffee738 402035f2  
08:59:35.168 -> 3ffefce0:  2f637364 00746553 3ffee738 40203508  
08:59:35.168 -> 3ffefcf0:  514d0401 00000001 3ffe8775 3ffee73c  
08:59:35.168 -> 3ffefd00:  3ffe84b4 00000000 3ffee738 40203456  
08:59:35.168 -> 3ffefd10:  3fffdad0 0000001f 3ffeed3c 3ffefd40  
08:59:35.204 -> 3ffefd20:  3fffdad0 00000001 3ffee738 40201f46  
08:59:35.204 -> 3ffefd30:  3fffdad0 00000000 3ffeed60 40201fa8  
08:59:35.204 -> 3ffefd40:  3fffdad0 3ffee80c 3ffeed3c 40204d74  
08:59:35.204 -> 3ffefd50:  3fffdad0 3ffee80c 3ffeed3c 4020236c  
08:59:35.204 -> 3ffefd60:  00000000 00000000 00000001 3ffeed68  
08:59:35.238 -> 3ffefd70:  3fffdad0 00000000 3ffeed60 4020501c  
08:59:35.238 -> 3ffefd80:  feefeffe feefeffe 3ffeed70 40100718  
08:59:35.238 -> <<<stack<<<

08:59:35.272 ->  ets Jan  8 2013,rst cause:2, boot mode:(3,6)
08:59:35.272 -> 
08:59:35.272 -> load 0x4010f000, len 1384, room 16 
08:59:35.272 -> tail 8
08:59:35.272 -> chksum 0x2d
08:59:35.272 -> csum 0x2d
08:59:35.272 -> v3ffe88b0
08:59:35.272 -> ~ld

08:59:35.505 -> 
WiFi connected: 192.168.1.41
08:59:36.516 -> MQTT connected: 192.168.1.30
08:59:36.516 -> DSC Keybus Interface is online.

>>> update
in tests I identified moment when it happens - each time when I try to send 1A over MQTT

**Comment by taligentx** [comment]
Hi @witek1308 - I haven't run into the WDT issues, if you're still running into this with the current esp8266 Arduino Core 2.5.1 please post a new issue and let's take a look.  Thanks!
