### ISSUE TITLE
Issue with Blynk code scanning

### ISSUE THREAD

**Issue by witek1308** [taligentx/dscKeybusInterface#52]
Hi,
I'm trying to scan Blync code on my Android (A5 2016) and I have probles as image is very dark itself and when trying to scan from the monitor it is hardly visible, phone doesn't capture it at all.
When I try to download image and open it with Blync it says - not valid QR code.

How did you solve this issue?

**Comment by taligentx** [comment]
I haven't been able to replicate this, if you still have this issue please re-open this issue and I'll take a look.
