### ISSUE TITLE
HTTP Server Example -Arm/Disarm not working

### ISSUE THREAD

**Issue by jjcuen** [taligentx/dscKeybusInterface#60]
Good morning 
I have (almost) successfully implemented HTTP Server example. Virtual keypad reads all messages and numeric buttons also write back into the key bus, however all the other "combo" buttons (stay arm, arm, etc.  ) do not work. 
When you press those buttons , it beeps on the virtual keypad and the serial output only sends  open/close braces {}.
I have a PC1616 system
Thanks!

**Comment by taligentx** [comment]
Hi @jjcuen - I've updated this example so the fire, alarm, panic, stay arm, away arm, and door chime buttons are functional.  If there are any issues with this in the current release please feel free to re-open this issue.  Thanks!
