### ISSUE TITLE
[Enhancement] Init value for Fire and Alarm status

### ISSUE THREAD

**Issue by MagnusPer** [taligentx/dscKeybusInterface#8]
WAIT - I WILL INSTEAD TRY TO HAVE MY OWN INIT IN THE BEGINING OF THE LOOP, IT MAY BE BETTER IF THIS IS CONTROLLED BY RESPECTIVELY IMPLEMENTATION

Provide an init value for at least Fire and Alarm at startup, meaning let the Change flag be true once.
- dsc.partitionAlarmChanged
- dsc.fireStatusChanged

The logic as of today provides updates only if there has been a status change. In the Homey app there is an absence of the status in the Fire and Tamper alarm device since nothing is provided. The status change for these are quite rare!

It may be needed to have a minor delay, or trigg on another status change in order to ensure listening systems such Homey is established.

```
// Publish alarm status to Homey
    if (dsc.partitionAlarmChanged) {
      dsc.partitionAlarmChanged = false;  // Resets the partition alarm status flag
      if (dsc.partitionAlarm) Homey.setCapabilityValue("alarm_tamper", true);
      else Homey.setCapabilityValue("alarm_tamper", false);
    }
```

**Comment by taligentx** [comment]
Ah, just saw your edit.  Sounds good.

By the way, if you get the Homey integration working to your satisfaction and think others would benefit (and would like to share the code), I can add your example to the library examples.

**Comment by MagnusPer** [comment]
No problem to share my example of integration to Homey when finished
